---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 59231.
--- DateTime: 2024/1/29 16:54
---
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]

local stockKey = 'seckill:stock:' .. voucherId

local orderKey = 'seckill:order:' .. voucherId
if (tonumber(redis.call('get', stockKey)) <= 0) then
    -- 库存不足 返回1
    return 1
end
if (redis.call('sismember', orderKey, userId) == 1) then
    -- 已经抢过了 返回2
    return 2
end

-- 库存减一
redis.call('incrby', stockKey, -1)
-- 记录用户id
redis.call('sadd', orderKey, userId)
-- 发送到消息队列
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0